### ISSUE TITLE
failed to build with ghc 8.0.1

### ISSUE THREAD

**Issue by Heather** [silkapp/rest#148]
```
src\Rest\Types\Void.hs:53:22: error:
    * Expected kind `Meta', but `D1Void' has kind `*'
    * In the first argument of `D1', namely `D1Void'
      In the type `D1 D1Void V1'
      In the type instance declaration for `Rep'
```

**Comment by hesselink** [comment]
Oh, I fixed this but it looks like I didn't release it. I'll make a release now.

**Comment by Heather** [comment]
@hesselink I was trying to build from `master` ...

**Comment by hesselink** [comment]
Oh, thanks, that's useful. I'll test again with GHC 8 on master.

**Comment by hesselink** [comment]
I've just tested again any my master builds correctly with GHC 8.0.1, building commit f45ff1fac5a11a06cb73113533503fad9931cc4b. What is the exact GHC version you're using, what commit are you building, and what build command are you using?

**Comment by hesselink** [comment]
I've also uploaded rest-types 1.14.1, which should build with GHC 8/

**Comment by Heather** [comment]
```
F:\P\thridparty\rest\rest-core>git rev-parse --abbrev-ref HEAD
master

F:\P\thridparty\rest\rest-core>git log -n 1 --pretty=format:%H
f45ff1fac5a11a06cb73113533503fad9931cc4b

F:\P\thridparty\rest\rest-core>ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1

F:\P\thridparty\rest\rest-core>ver

Microsoft Windows [Version 10.0.10586]

F:\P\thridparty\rest\rest-core>cabal install
Resolving dependencies...
Configuring rest-types-1.14.0.1...
Building rest-types-1.14.0.1...
Failed to install rest-types-1.14.0.1
Build log ( C:\Users\H\AppData\Roaming\cabal\logs\rest-types-1.14.0.1.log ):
Building rest-types-1.14.0.1...
Preprocessing library rest-types-1.14.0.1...
[1 of 8] Compiling Rest.Types.ShowUrl ( src\Rest\Types\ShowUrl.hs, dist\build\Rest\Types\ShowUrl.o )
[2 of 8] Compiling Rest.Types.Range ( src\Rest\Types\Range.hs, dist\build\Rest\Types\Range.o )
[3 of 8] Compiling Rest.Types.Info  ( src\Rest\Types\Info.hs, dist\build\Rest\Types\Info.o )
[4 of 8] Compiling Rest.Types.Void  ( src\Rest\Types\Void.hs, dist\build\Rest\Types\Void.o )

src\Rest\Types\Void.hs:53:22: error:
    * Expected kind `Meta', but `D1Void' has kind `*'
    * In the first argument of `D1', namely `D1Void'
      In the type `D1 D1Void V1'
      In the type instance declaration for `Rep'
cabal: Leaving directory 'C:\Users\H\AppData\Local\Temp\cabal-tmp-1992\rest-types-1.14.0.1'
cabal: Error: some packages failed to install:
rest-core-0.39 depends on rest-types-1.14.0.1 which failed to install.
rest-types-1.14.0.1 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by Heather** [comment]
seems like I should build types from `master` before `core` and it was just my mistake :S

**Comment by hesselink** [comment]
Great, that helps! So while you're building `rest-core` from git, it's pulling `rest-types` from hackage. A `cabal update` should fix it, or build `rest-types` from git as well, like you said.

**Comment by hesselink** [comment]
Still, thanks for reporting, since I forgot to upload rest-types!
